POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "kxzb",
  "name": "kxzb",
  "password": "123456"
}

# {
#   "username": "root",
#   "name": "Superuser",
#   "password": "salainen"
# }
